version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: appnotify-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:16.0
    container_name: appnotify-postgres
    environment:
      POSTGRES_DB: appnotify
      POSTGRES_USER: appnotify
      POSTGRES_PASSWORD: appnotify
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  mongodb:
    image: mongo:6.0
    container_name: appnotify-mongodb
    command: ["--replSet", "rs0", "--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: appnotify
      MONGO_INITDB_ROOT_PASSWORD: appnotify
      MONGO_INITDB_DATABASE: appnotify
    ports:
      - "27017:27017"   # MongoDB (usuario: appnotify, password: appnotify)
    volumes:
      - mongo-data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  backend:
    build: ./backend
    container_name: appnotify-backend
    depends_on:
      - rabbitmq
      - postgres
      - mongodb
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appnotify
      SPRING_DATASOURCE_USERNAME: appnotify
      SPRING_DATASOURCE_PASSWORD: appnotify
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATA_MONGODB_URI: mongodb://appnotify:appnotify@mongodb:27017/appnotify?authSource=admin&replicaSet=rs0
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    container_name: appnotify-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres-data:
  mongo-data: